# Generated by Django 2.2.28 on 2023-07-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_helloo'),
    ]

    operations = [
        migrations.AddField(
            model_name='helloo',
            name='sdsd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
