# Generated by Django 2.2.28 on 2023-07-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_helloo_sdsd'),
    ]

    operations = [
        migrations.AddField(
            model_name='helloo',
            name='ddsdssd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
