# Generated by Django 2.2.28 on 2023-07-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_helloo_ddsdssd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sddsds', models.BigIntegerField()),
            ],
        ),
    ]
