# Generated by Django 2.2.28 on 2023-07-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_hi'),
    ]

    operations = [
        migrations.AddField(
            model_name='hi',
            name='daddsadds',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
