# Generated by Django 2.2.28 on 2023-07-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_hi_daddsadds'),
    ]

    operations = [
        migrations.AddField(
            model_name='hi',
            name='sddsd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
